# Generated by Django 6.1.1 on 2026-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('name', models.CharField(max_length=20)),
                ('github', models.URLField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
